package dev.maxsiomin.capitals.util

val europe = mapOf(
    "Greece" to "Athens",
    "Serbia" to "Belgrade",
    "Germany" to "Berlin",
    "Slovakia" to "Bratislava",
    "Belgium" to "Brussels",
    "Romania" to "Bucharest",
    "Hungary" to "Budapest",
    "Denmark" to "Copenhagen",
    "Ireland" to "Dublin",
    "Finland" to "Helsinki",
    "Ukraine" to "Kyiv",
    "Portugal" to "Lisbon",
    "Slovenia" to "Ljubljana",
    "United Kingdom" to "London",
    "Spain" to "Madrid",
    "Belarus" to "Minsk",
    "Russia" to "Moscow",
    "Norway" to "Oslo",
    "France" to "Paris",
    "Czech Republic" to "Prague",
    "Latvia" to "Riga",
    "Italy" to "Rome",
    "Bosnia and Herzegovina" to "Sarajevo",
    "North Macedonia" to "Skopje",
    "Bulgaria" to "Sofia",
    "Sweden" to "Stockholm",
    "Estonia" to "Tallinn",
    "Albania" to "Tirana",
    "Austria" to "Vienna",
    "Poland" to "Warsaw",
    "Croatia" to "Zagreb",
)

val africa = mapOf(
    "Ghana" to "Accra",
    "Nigeria" to "Abuja",
    "Algeria" to "Algiers",
    "Eritrea" to "Asmara",
    "Mali" to "Bamako",
    "Egypt" to "Cairo",
    "Guinea" to "Conakry",
    "Senegal" to "Dakar",
    "Botswana" to "Gaborone",
    "Zimbabwe" to "Harare",
    "Uganda" to "Kampala",
    "Sudan" to "Khartoum",
    "Rwanda" to "Kigali",
    "Gabon" to "Libreville",
    "Malawi" to "Lilongwe",
    "Angola" to "Luanda",
    "Zambia" to "Lusaka",
    "Lesotho" to "Maseru",
    "Somalia" to "Mogadishu",
    "Liberia" to "Monrovia",
    "Kenya" to "Nairobi",
    "Mauritania" to "Nouakchott",
    "Morocco" to "Rabat",
    "Libya" to "Tripoli",
    "Tunisia" to "Tunis",

)

val asia = mapOf(
    "Jordan" to "Amman",
    "Turkmenistan" to "Ashgabat",
    "Iraq" to "Baghdad",
    "Thailand" to "Bangkok",
    "China" to "Beijing",
    "Lebanon" to "Beirut",
    "Kyrgyzstan" to "Bishkek",
    "Syria" to "Damascus",
    "Bangladesh" to "Dhaka",
    "Qatar" to "Doha",
    "Tajikistan" to "Dushanbe",
    "Vietnam" to "Hanoi",
    "Pakistan" to "Islamabad",
    "Indonesia" to "Jakarta",
    "Nepal" to "Kathmandu",
    "Oman" to "Muscat",
    "Myanmar" to "Naypyidaw",
    "South Korea" to "Seoul",
    "Uzbekistan" to "Tashkent",
    "Iran" to "Tehran",
    "Japan" to "Tokyo",
    "Mongolia" to "Ulaanbaatar",

)

val america = mapOf(
    "Venezuela" to "Caracas",
    "Guyana" to "Georgetown",
    "Peru" to "Lima",
    "Uruguay" to "Montevideo",
    "Ecuador" to "Quito",
    "Belize" to "Belmopan",
    "Nicaragua" to "Managua",
    "Canada" to "Ottawa",
    "United States" to "Washington",
    "Chile" to "Santiago",
)

val allCountriesWithCities = europe + africa + asia + america

val allCitiesOnly = allCountriesWithCities.values
